baseURL: https://setsevireon.github.io/photophobia/
languageCode: en-us
theme: github.com/setsevireon/photophobia

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ""

languages:
  en:
    title: Latim Jibber Jabber
    weight: 1
    contentDir: content/en
  pt:
    title: Lero Lero Latim
    weight: 2
    contentDir: content/pt

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

params:
  favicon: null
  site_logo: null
  description: Pellentesque commodo dolor leo.
  recent_posts_number: 10

markup:
  highlight:
    style: native
